require:
  - rubocop-rails

AllCops:
  Exclude:
  - 'bin/**/*'
  - 'log/**/*'
  - 'public/**/*'
  - 'storage/**/*'
  - 'tmp/**/*'
  - 'vendor/**/*'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false
