development:
  adapter: postgresql
  host: <%= ENV.fetch('RAILS_DBHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('RAILS_DBPORT', '5432') %>
  username: <%= ENV.fetch('RAILS_DBUSERNAME', 'railsdev') %>
  password: <%= ENV.fetch('RAILS_DBPASSWORD', 'password') %>
  database: worklogsapp_development
  schema_search_path: public
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 2) %>
  min_messages: log

test:
  adapter: postgresql
  host: <%= ENV.fetch('RAILS_DBHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('RAILS_DBPORT', '5432') %>
  username: <%= ENV.fetch('RAILS_DBUSERNAME', 'railsdev') %>
  password: <%= ENV.fetch('RAILS_DBPASSWORD', 'password') %>
  database: worklogsapp_test
  schema_search_path: public
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 2) %>
  min_messages: log

production:
  adapter: postgresql
  url: <%= ENV.fetch('DATABASE_URL', 'postgres://user:password@hostname:port/db') %>
  schema_search_path: public
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 2) %>
  min_messages: warning
